#cloud-config
package_update: true
package_upgrade: true
packages:
    - build-essential
    - unzip
    - jq
    - git
    - ssh-import-id
snap:
    commands:
      00: snap install yq
output: {all: '| tee -a /var/log/cloud-init-output.log'}