#cloud-config
package_update: true
package_upgrade: true
packages:
    - build-essential
    - unzip
    - jq
    - git
    - ssh-import-id
    - curl
    - apt-transport-https 
    - ca-certificates 
    - software-properties-common
runcmd:
  - ['sh', '-c', 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg']
  - ['sh', '-c', 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null']
  - ['sh', '-c', 'apt-get -o Acquire::ForceIPv4=true update']
  - ['sh', '-c', 'apt-get -o Acquire::ForceIPv4=true install -y docker-ce docker-compose-plugin']
  - ['sh', '-c', 'systemctl enable --now docker']
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}